FROM node as builder

WORKDIR /react-app

ENV PATH /react-app/node_modules/.bin:$PATH

COPY ./react/package.json ./
RUN npm install 

COPY react .
RUN npm run build

FROM nginx

COPY --from=builder /react-app/build/ /home/app/web/build/

COPY nginx/production/nginx.conf /etc/nginx/conf.d/default.conf
