name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd template
            docker-compose -f development.yml down --remove-orphans
            git pull origin master
            docker-compose -f development.yml build
            docker-compose -f development.yml up -d
            echo 'done'
            
  
